### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by belleh71513**
學員:王崇維
繳交第 3 週作業
http://54.89.137.58:3000/
http://54.89.137.58:3000/attraction/19

### CODE REVIEW

**Comment by cwpeng** [comment]
Try to align with design in details.
1. Bottom line of navigator should be only 1px height with lighter grey.
2. More margin spaces between attraction mrt and order box.
3. Separator line in middle is under order box in mobile version.

未命名-5
未命名-6

**Comment by belleh71513** [comment]
依照審查意見修改後再次提交
http://54.89.137.58:3000/
http://54.89.137.58:3000/attraction/19

**Comment by cwpeng** [comment]
Issues in screen width 360px.

未命名-8

**Comment by belleh71513** [comment]
modified again according to comments

http://54.89.137.58:3000/
http://54.89.137.58:3000/attraction/19 #

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
